name: Node.js 18 Build and Publish

on:
  push:
    branches:
      - main
      - ci

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Check dir
        run: ls -l -all

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint package
        run: pnpm nx lint vault

      - name: Test package
        run: pnpm nx test vault

      - name: Build package
        run: pnpm nx build vault

      - name: Copy README
        run: cp README.md dist/packages/vault/README.md

      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public dist/packages/vault
